### ISSUE TITLE
Zray toolbar not displayed in oro pages

### ISSUE THREAD

**Issue by stalxed** [orocrm/zray#3]
Zray toolbar good work on:
- zend server admin panel(Zray live)
- oro login page
- symfony exceptions page(when use app_dev.php)

But! Zray toolbar not work on other oro pages.

I think zray toolbar and oro html conflict with each other.

This can somehow fix it?

**Comment by DimaSoroka** [comment]
hi @stalxed 

Just to clarify, do you have an issue with ZRay toolbar and Symfony dev toolbar working together?
ZRay toolbar works just fine and tracks every request.

Please provide more details on this issue and your environment information.

**Comment by stalxed** [comment]
Здравствуйте @DimaSoroka 

Надеюсь можно по русски? По английски тяжело описать всю ситуацию.

Zray работает отлично, т.е. все запросы видны в админке Zend Server(секция zray live).
Так же zray toolbar отображается и работает на странице входа в oro platform, страницах эксепшенов.
Но на основных страницах zray toolbar не работает.

Мне кажется, что попросту конфликтует вёрстка oro platform и zray toolbarа.

Так как запрос к zend server выполняется только при первой загрузке страницы,  дальше, когда выполняются ajax запросы, при переходах между страницами, запросов к zend server вообще нет. Это информацию смотрю через снифер.

Когда zray тулбар не работает он просто пишет Loading Z-Ray...

У меня develop машина:
- windows 8.1
- Zend Server Version: 8.0.2 Build: 95060 Profile: Development 
- oro/platform 	1.6.1

**Comment by DimaSoroka** [comment]
День добрый!

Все запросы отлавливаются, их можно увидеть в левом нижнем углу (там будет статус последнего, как правило 200). По нажатию открывается список всех AJAX запросов и можно выбрать нужный.

Спасибо

**Comment by stalxed** [comment]
А у меня выглядит примерно так:
![screen](https://cloud.githubusercontent.com/assets/3492910/7131379/3fa9f544-e287-11e4-9a43-29ba71a47e4a.PNG)
И дальше не прогружается.

Но например на странице входа всё ок:
![screen2](https://cloud.githubusercontent.com/assets/3492910/7131391/7cf1d016-e287-11e4-8254-d103551c65c0.PNG)

В обоих случаях в админке запросы видны, и вся информация собрана.
Может быть какой-то конфликт в ява скриптах между oro platform и zray?

**Comment by stalxed** [comment]
Нашёл баг:
В файле C:\ZendServer\gui\module\DevBar\src\DevBar\View\Helper\ExceptionsJson.php
изменил метод с
``` php
	public function __invoke($exceptions) {
		$entries = array();
		foreach ($exceptions as $exception) {
			$entries[] = $this->exceptionInfo($exception);
		}

		return $this->getView()->json($entries);
	}
```
на

``` php
	public function __invoke($exceptions) {
		$entries = array();
		foreach ($exceptions as $exception) {
			$entries[] = $this->exceptionInfo($exception);
		}
		
		$defaultValue = \Zend\Json\Json::$useBuiltinEncoderDecoder;
		\Zend\Json\Json::$useBuiltinEncoderDecoder = true;

		$json = $this->getView()->json($entries);
		
		\Zend\Json\Json::$useBuiltinEncoderDecoder = $defaultValue;
		
		return $json;
	}
```
Видать часть эксепшенов их собственная реализация json encoder не cмогла правильно перевести в JSON. В данном фрагменте я переключил временно, на время работы этой функции на родной PHP json encoder.

Чуть позже отправлю репорт Zendу.

Кстати, ~200 эксепшенов показывается в чистой OroCRM 1.6.1.
Это пугающее число, в нём нет ничего страшного? В основном это сообщения типа:
- There is no ACL for the given object identity.
- Unable to find template

**Comment by stalxed** [comment]
About bug created thread in the forum http://forums.zend.com/viewtopic.php?f=8&t=126708
Problem in the Zend Server, and not in Oro.
Close the ticket.
